extends:
  - 'next/core-web-vitals'
  - '@imhoff/eslint-config/recommended'
plugins:
  - 'import-alias'
rules:
  import-alias/import-alias:
    - error
    - relativeDepth: 1
      aliases:
        - alias: '@src'
          matcher: '^src'
  import/order:
    - error
    - alphabetize:
        order: asc
        caseInsensitive: false
      groups:
        - [builtin, external]
        - parent
        - [sibling, index]
      pathGroups:
        - pattern: '@src/**'
          group: parent
          position: before
      pathGroupsExcludedImportTypes:
        - builtin
      newlines-between: always
