import type { NextPage } from 'next'
import Head from 'next/head'
import { styled } from '../stitches.config'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Title>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Title>
      </Main>
    </>
  )
}

const Main = styled('main', {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
})

const Title = styled('h1', {
  '& a': {
    color: '#0070f3',
  },
})

export default Home
